<% web_pool_size = (ENV['DATABASE_POOL'] || ENV['RAILS_MAX_THREADS'] || 5).to_i %>

default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= web_pool_size %>

development:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  username: postgres
  password: postgres
  database: development

test:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  username: postgres
  password: postgres
  database: test

production:
  url: <%= ENV['DATABASE_URL'] %>
